# This is a basic workflow to help you get started with Actions

name: Deploy to Non Prod Private space

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code repository
        uses: actions/checkout@v4
      # Cache the dependencies
      #- name: Set up JDK 11
       # uses: actions/setup-java@v1
        #with:
         #     java-version: 11
      # Step that does that actual cache save and restore
     # - uses: actions/cache@v4
      #  with:
       #   path: ~/.m2/repository
        #  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
         # restore-keys: |
          #  ${{ runner.os }}-maven-

      # Build and upload the artefact to exchange
      - name: Build artefact and upload to exchange
        run: mvn clean deploy -s .maven/settings.xml

      # Deploy the artefact from exchange
      - name: Deploy the artefact from exchange
        run: mvn clean deploy -DmuleDeploy -s .maven/settings.xml
